version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "agavrilov76"
      - "madsholden"
    ignore:
      - depencency-name: org.restcomm.smpp:ch-smpp
    groups:
      patches:
        update-types:
          - "minor"
          - "patch"
